# prometheus.yml
global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'nginx'
    static_configs:
      - targets: ['web-server:80']
    metrics_path: /metrics

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['web-server:9100']