- name: Install nginx
  apt:
    name: nginx
    state: present
    update_cache: yes
  become: yes
  register: nginx_install

- name: Stop nginx service before configuration
  service:
    name: nginx
    state: stopped
  become: yes
  when: nginx_install.changed

- name: Ensure /var/www exists
  file:
    path: /var/www
    state: directory
    mode: '0755'
  become: yes

- name: Remove existing html directory if present
  file:
    path: /var/www/html
    state: absent
  become: yes

- name: Clone website repository to /var/www
  git:
    repo: https://github.com/Raghavarora09/aws-infra-automation-monitoring.git
    dest: /var/www
    force: no
    version: main
    depth: 1
  become: yes
  ignore_errors: no

- name: Set correct ownership and permissions
  file:
    path: /var/www
    owner: www-data
    group: www-data
    recurse: yes
    mode: 'u=rwX,go=rX'
  become: yes

- name: Start nginx
  service:
    name: nginx
    state: started
  become: yes
