---
- name: Install nginx
  apt:
    name: nginx
    state: present
    update_cache: yes
  become: yes

- name: Configure nginx
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify: restart nginx
  become: yes

- name: Create website directory
  file:
    path: /var/www/html
    state: directory
    mode: '0755'
  become: yes

- name: Clone website repository
  git:
    repo: https://github.com/Raghavarora09/aws-infra-automation-monitoring.git
    dest: /tmp/website
    version: main
  become: yes

- name: Copy website files
  copy:
    src: /tmp/website/aws-infra-automation-monitoring/website/
    dest: /var/www/html/
    owner: nginx
    group: nginx
    mode: '0644'
  become: yes

- name: Upload website files to S3 bucket
  amazon.aws.aws_s3:
    bucket: "{{ s3_bucket_name }}"
    object: "{{ item }}"
    src: "/tmp/website/{{ item }}"
    mode: put
  with_fileglob:
    - /tmp/website/*
  become: yes

- name: Download website files from S3
  amazon.aws.aws_s3:
    bucket: "{{ s3_bucket_name }}"
    object: "{{ item }}"
    dest: "/var/www/html/{{ item }}"
    mode: get
  become: yes
  with_items:
    - index.html
    - styles.css
    - script.js