- name: Install nginx
  apt:
    name: nginx
    state: present
    update_cache: yes
  become: yes

- name: Configure nginx
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify: restart nginx
  become: yes

- name: Create website directory
  file:
    path: /var/www/html
    state: directory
    mode: '0755'
  become: yes

- name: Remove existing website files
  file:
    path: /var/www/html
    state: absent
  become: yes

- name: Clone website repository directly to web root
  git:
    repo: https://github.com/Raghavarora09/aws-infra-automation-monitoring.git
    dest: /var/www/html
    force: yes
    version: main
    depth: 1
  become: yes

  - name: Set correct ownership and permissions
  file:
    path: /var/www/html
    owner: www-data
    group: www-data
    recurse: yes
    mode: 'u=rwX,go=rX'
  become: yes
