name: Deploy Infrastructure and Website

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: |
        cd terraform
        terraform init

    - name: Terraform Plan
      run: |
        cd terraform
        terraform plan -var="bucket_name=${{ secrets.S3_BUCKET_NAME }}" \
                      -var="ami_id=${{ secrets.AMI_ID }}" \
                      -var="key_name=${{ secrets.SSH_KEY_NAME }}" \
                      -var="admin_ip=${{ secrets.ADMIN_IP }}"

    - name: Terraform Apply
      if: github.ref == 'refs/heads/main'
      run: |
        cd terraform
        terraform apply -auto-approve \
                       -var="bucket_name=${{ secrets.S3_BUCKET_NAME }}" \
                       -var="ami_id=${{ secrets.AMI_ID }}" \
                       -var="key_name=${{ secrets.SSH_KEY_NAME }}" \
                       -var="admin_ip=${{ secrets.ADMIN_IP }}"

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Ansible
      run: |
        python -m pip install --upgrade pip
        pip install ansible boto3

    - name: Run Ansible Playbook
      run: |
        cd ansible
        ansible-playbook -i inventory/aws_ec2.yml playbook.yml